# Generated by Django 4.0.2 on 2022-02-27 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='default_shop_product', force_format=None, keep_meta=True, null=True, quality=0, size=[370, 530], upload_to='product_images')),
                ('cover_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='default_shop_product', force_format=None, keep_meta=True, null=True, quality=0, size=[370, 530], upload_to='product_images')),
                ('label_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='default_shop_product', force_format=None, keep_meta=True, null=True, quality=0, size=[370, 530], upload_to='product_images')),
                ('kensa_bango', models.IntegerField(blank=True, null=True)),
                ('kensa_id', models.IntegerField(blank=True, null=True)),
                ('shouhinmei', models.CharField(blank=True, max_length=60, null=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
