# Generated by Django 4.0.2 on 2022-02-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, default='default_shop_product', null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_shop_product', null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label_image',
            field=models.ImageField(blank=True, default='default_shop_product', null=True, upload_to='product_images'),
        ),
    ]
