# Generated by Django 4.0.2 on 2022-03-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_image_similarity_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gazo_bango',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_bango',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
